server:
  port: 8662

spring:
  application:
    name: gateway-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

zuul:
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  ignored-service: '*'
  routes:
    chat-service:
      path: /chat/**
      serviceId: chat-service
      stripPrefix: true
    user-service:
      path: /user/**
      serviceId: user-service
      stripPrefix: true
    authentication-service:
      path: /auth/**
      serviceId: authentication-service
      stripPrefix: true
    course-service:
      path: /course/**
      serviceId: course-service
      stripPrefix: true
    school-service:
      path: /school/**
      serviceId: school-service
      stripPrefix: true
    notifications-service:
      path: /notification/**
      serviceId: notifications-service
      stripPrefix: true
    meetings-service:
      path: /meeting/**
      serviceId: meetings-service
      stripPrefix: true
    schedule-presence-service:
      path: /schedule-presence/**
      serviceId: schedule-presence-service
      stripPrefix: true